[general]

import = ["/home/kintsugi/.config/alacritty/themes/dark/kitty.toml"]


# Cascadia
[font]
size = 16
normal = { family = "Cascadia Code", style = "Medium" }
bold = { family = "Cascadia Code", style = "Bold" }
italic = { family = "Cascadia Code", style = "Italic" }
bold_italic = { family = "Cascadia Code", style = "Bold Italic" }
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }

# Jet Brains 
# [font]
# size = 16
# normal = { family = "JetBrainsMonoNL Nerd Font", style = "Light" }
# bold = { family = "JetBrainsMonoNL Nerd Font", style = "Bold" }
# italic = { family = "JetBrainsMonoNL Nerd Font", style = "Medium Italic" }
# bold_italic = { family = "JetBrainsMonoNL Nerd Font", style = "Bold Italic" }

[window]
opacity = 1
dimensions = { columns = 80, lines = 20 }
startup_mode = "Windowed"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval = 500
unfocused_hollow = true
