[general]

import = ["/home/kintsugi/.config/alacritty/themes/dark/aura.toml"]


# Cascadia
[font]
size = 16.5
normal = { family = "Cascadia Code NF", style = "Regular" }
bold = { family = "Cascadia Code NF", style = "Bold" }
italic = { family = "Cascadia Code NF", style = "Italic" }
bold_italic = { family = "Cascadia Code NF", style = "Bold Italic" }
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }

# Jet Brains 
# [font]
# size = 16.5
# normal = { family = "JetBrainsMonoNL Nerd Font", style = "Regular" }
# bold = { family = "JetBrainsMonoNL Nerd Font", style = "ExtraBold" }
# italic = { family = "JetBrainsMonoNL Nerd Font", style = "Medium Italic" }
# bold_italic = { family = "JetBrainsMonoNL Nerd Font", style = "Bold Italic" }
# offset = { x = 0, y = 0 }
# glyph_offset = { x = 0, y = 0 }


[window]
opacity = 0.95
dimensions = { columns = 80, lines = 20 }
startup_mode = "Windowed"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval = 500
unfocused_hollow = true
